---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGZvam9udG1j 
  CLOUDINARY_KEY: MjQ2Njk0MTMyNjMxMTM2
  CLOUDINARY_SECRET: OWd3b1Z4NGlRaEpJYkNGazk4bV9nNENLQ1dv
  MAPBOX_TOKEN: cGsuZXlKMUlqb2ljSEpoZEdoNWRYTm9ZbWhoYm5VaUxDSmhJam9pWTJ4M2RuVnNNMnRvTUhObk5ESnFjMkZ6T0RoellqYzJNU0o5LnNCc1JibEFrcUxyNmxrUzM1bUlnakE=
  DB_URL: bW9uZ29kYitzcnY6Ly9hYnByYXRoeXVzaDpIaWdob25jb2tlMjQ3JEBteS1jbHVzdGVyLmV6ZmtjdWUubW9uZ29kYi5uZXQvYmhhbnUtZGI/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5
  SECRET: ZWlic2pFUTF3SjRPRmRab1daZ2JCZnN4VUVJSlFRVlpmdzMtLXM1ZXFpVQ==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: doper129/bhanu-three-tier:latest
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
